### ISSUE TITLE
Release Cake.Bridge vNext compatible with Cake v1.2.0

### ISSUE THREAD

**Issue by augustoproiete** [devlead/Cake.Bridge#5]
Cake v1.2.0 introduced a new [`GetArguments` method via PR 3388](https://github.com/cake-build/cake/pull/3388) that [breaks Cake.Bridge.DependencyInjection](https://github.com/devlead/Cake.Bridge.DependencyInjection/issues/1) which will need to be updated to target Cake v1.2.0.

It would be good to update Cake.Bridge target Cake v1.2.0 as well, in advance of https://github.com/devlead/Cake.Bridge.DependencyInjection/issues/1

**Comment by devlead** [comment]
Fixed with https://www.nuget.org/packages/Cake.Bridge/0.0.19-alpha
